# Generated by Django 3.0 on 2020-03-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loginTime',
        ),
    ]
