# Generated by Django 3.0 on 2020-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_logintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=12),
            preserve_default=False,
        ),
    ]
