# Generated by Django 3.0 on 2020-03-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
